// <auto-generated />
using System;
using GiulioCardillo.Exercize1.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GiulioCardillo.Exercize1.Persistence.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GiulioCardillo.Exercise1.Domain.Market", b =>
                {
                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MarketId");

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("GiulioCardillo.Exercise1.Domain.Phone", b =>
                {
                    b.Property<Guid>("PhoneId")
                        .HasColumnType("uuid");

                    b.Property<int>("Battery")
                        .HasColumnType("integer");

                    b.Property<int>("Camera")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<int>("Screen")
                        .HasColumnType("integer");

                    b.HasKey("PhoneId");

                    b.HasIndex("MarketId");

                    b.ToTable("Phone");
                });

            modelBuilder.Entity("GiulioCardillo.Exercise1.Domain.Phone", b =>
                {
                    b.HasOne("GiulioCardillo.Exercise1.Domain.Market", null)
                        .WithMany("Phones")
                        .HasForeignKey("MarketId");
                });

            modelBuilder.Entity("GiulioCardillo.Exercise1.Domain.Market", b =>
                {
                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
